// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEzxZfAc71hzmsh7wDHw94NV1435UZz8',
    appId: '1:707718886610:web:b2543b7cfaaa80eb8ce90b',
    messagingSenderId: '707718886610',
    projectId: 'campusconnect-cb336',
    authDomain: 'campusconnect-cb336.firebaseapp.com',
    storageBucket: 'campusconnect-cb336.firebasestorage.app',
    measurementId: 'G-N8KJB4DYG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6rjap3fwiBNdtWUO5QQtGRLoFHl1tkg',
    appId: '1:707718886610:android:6a0df7cb133f7df28ce90b',
    messagingSenderId: '707718886610',
    projectId: 'campusconnect-cb336',
    storageBucket: 'campusconnect-cb336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNlVAwtczfswNNfYzBCg-JHSznMhJe8k',
    appId: '1:707718886610:ios:cb70356554d4ce238ce90b',
    messagingSenderId: '707718886610',
    projectId: 'campusconnect-cb336',
    storageBucket: 'campusconnect-cb336.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNlVAwtczfswNNfYzBCg-JHSznMhJe8k',
    appId: '1:707718886610:ios:cb70356554d4ce238ce90b',
    messagingSenderId: '707718886610',
    projectId: 'campusconnect-cb336',
    storageBucket: 'campusconnect-cb336.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEzxZfAc71hzmsh7wDHw94NV1435UZz8',
    appId: '1:707718886610:web:fbc3b83e5218d7c08ce90b',
    messagingSenderId: '707718886610',
    projectId: 'campusconnect-cb336',
    authDomain: 'campusconnect-cb336.firebaseapp.com',
    storageBucket: 'campusconnect-cb336.firebasestorage.app',
    measurementId: 'G-WFKLZRJ3YQ',
  );
}
